spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.88.129:8848
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"